DEBUG 2018-11-28 19:14:44,512: 	 Executing command: 'submit'
DEBUG 2018-11-28 19:14:44,512: 	 Found CRAB cache file /afs/cern.ch/user/e/ebossini/.crab3
DEBUG 2018-11-28 19:14:44,521: 	 Checking credentials
DEBUG 2018-11-28 19:14:44,522: 	 Found proxy file /tmp/x509up_u3637
DEBUG 2018-11-28 19:14:44,522: 	 Getting proxy life time left
DEBUG 2018-11-28 19:14:45,330: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u3637 -timeleft
 output : 43033

 error: 
 retcode : 0
DEBUG 2018-11-28 19:14:46,039: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u3637 -actimeleft
 output : 43033

 error: 
 retcode : 0
DEBUG 2018-11-28 19:14:46,039: 	 Proxy valid for 11:57:13 hours
ERROR 2018-11-28 19:14:46,040: 	 CRAB configuration file crabConfig.py not found.
ERROR 2018-11-28 19:14:46,040: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
